### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by stes** [abarbu/objectnet-template-pytorch#12]
Hi, thanks a lot for your example code.

Is it intentional that the repository is distributed with [No License](https://choosealicense.com/no-permission/) currently? If not, could you add a `LICENSE` to the repository? Thanks a lot for looking into it!

**Comment by abarbu** [comment]
Thanks for the heads up, you're completely right!
The repo is now MIT licensed, which should give everyone maximal freedom.
Let us know if you find any other issues.

**Comment by stes** [comment]
Perfect, thanks a lot!
